include "tag.thrift"
include "section.thrift"

namespace scala com.gu.tagmanagement

enum OperationType {
    /** add the given tag to the top of the content's tag list - generated by batch tagging */
    ADD_TO_TOP = 0,

    /** add the given tag to the bottom of the content's tag list - generated by batch tagging */
    ADD_TO_BOTTOM = 1,

    /** remove the given tag to the content's tag list - generated by batch tagging and tag delete */
    REMOVE = 3,

    /** replace the given tag with the destination tag in the content's tag list (or remove the given tag if the content has both) - generated by merge tag */
    MERGE = 4,

    /** reindex the given content item to reflect updates to that tag's content - generated when mappings are updated */
    REINDEX = 5
}

/** tuple with a tag and the denormalised section (as specified by the tag's section id) */
struct TagWithSection {

    /** the tag */
    1: required tag.Tag tag;

    /** the section, note this can be missing which some systems might need to pretend is the non-indexed 'global' section */
    2: optional section.Section section;
}

struct TaggingOperation {
    /** the tagging operation this represents */
    1: required OperationType operation;

    /** the content that this operation applies to */
    2: required string contentPath;

    /** the full representation of the tag in this operation (I.E. being added, removed or merged.) */
    3: optional TagWithSection tag;

    /** used for merge tag operation this is the tag to be used insted of the tag defined in the tag field */
    4: optional TagWithSection destinationTag;
}

