# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:

  # Manual invocation.
  workflow_dispatch:

  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: 'package-lock.json'

      - name: Setup Scala
        uses: guardian/setup-scala@v1

      - name: Install NPM dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Build icons
        run: npm run build-icons

      - name: SBT
        run: sbt clean compile test Debian/packageBin

      # Make the filename produced by SBT easier.
      - name: Rename debian artifact
        run: mv target/tag-manager_1.0_all.deb target/tag-manager.deb

      - uses: guardian/actions-riff-raff@v2
        with:
          projectName: editorial-tools:tag-manager
          buildNumberOffset: 1654
          configPath: riff-raff.yaml
          contentDirectories: |
            cloudformation:
              - cloudformation/tag-manager.yaml
            cloudformation-pillar-db:
              - cloudformation/pillar-dynamo.yaml
            cloudformation-pillar-audit-db:
              - cloudformation/pillar-audit-dynamo.yaml
            tag-manager:
              - target/tag-manager.deb
        
      - name: Upload certificates project to riff-raff
        uses: guardian/actions-riff-raff@v2
        with:
          configPath: certificates-riff-raff.yaml
          projectName: editorial-tools:tag-manager-certificates
          buildNumberOffset: 1654
          contentDirectories: |
            cloudformation:
            - cloudformation/tag-manager-certificates.yaml